### ISSUE TITLE
figure insert in markdown

### ISSUE THREAD

**Issue by perrette** [ISI-MIP/isipedia-library#1]
Background: @rgieseke and I discussed about how to handle figures insert. The parser should generate:
- HTML figure for the online version
- static figure (png or pdf) for the PDF version
- ideally gitlab would also display the (static?) figure when visualizing pre-processed markdown

The problem can be broken down in 
1. A syntax for the template (similar to current cube syntax)
2. How should the markdown report look like after template-processing? Or more precisely, how to keep the information so that both PDF and HTML creation are possible in the end?

As far as 1. is concerned, we will have something analogous to current cube manual (CDLX markdown command): `(line-plot: first-file-name,second-file-name first-temperature: 2 second-scenario: rcp60 second-time: 2041-2060)`, to be determined soon.

Now for 2, I have two thoughts.
- For the first question, how should the pre-processed markdown look like, an acceptable [gitlab syntax](https://docs.gitlab.com/ee/user/markdown.html) is: `![alt text1](#figurecode/figure.png "Title text")`

This can be convenient to link one figure to a `#figurecode` folder. In the folder we can have more things like pdf/png/html related to the figure, including a log of what went into it or underlying json data that can be downloaded.

- Additionally and besides that, I wonder how much we actually need a 'processed markdown', since in fact we only need HTML and PDF versions of the report.

**Comment by rgieseke** [comment]
something like

```

![This is the figcaption](test.png)
```
would suffice i think.

Or something like

```
![This is the figcaption](line-plot_first-file-name_second-file-name__first-temperatture.png)
```

In the processing for the website this would be converted to something like

```html
<div id="line-plot_first-file-name_second-file-name__first-temperature"></div>
```

when creating the HTML page.

**Comment by perrette** [comment]
Right, I'm nearly there.
I'm implementing matplotlib + mpld3 for now.
Option to create both png and mpld3 json, they are saved with the same id and different extensions.
Insert png link by default.
More tomorrow.

**Comment by perrette** [comment]
(it needs debugging, but you can get the idea already: https://github.com/ISI-MIP/isipedia-library/blob/master/isipedia/figure.py)

**Comment by perrette** [comment]
Works !
AFG and world so far. 

https://gitlab.pik-potsdam.de/isipedia/extremes/blob/master/cube/drought/future-projections/AFG/drought-AFG.md

From syntax `{{lineplot(land_abs_time)}}` which I'd qualify an improvement : )
Will add some more functions such as `lineplot2` (two figures as subplot), and `map`. 
But first I want to add the ranking.

**Comment by perrette** [comment]
Ah. Figures are in a sub-directory `figures` to limit the mess and ease `cleanfigure`.

**Comment by rgieseke** [comment]
Beauty!

**Comment by perrette** [comment]
I just updated the other areas.
Is it worth trying to include the mpld3 interactive figure in the HTML or you prefer to go straight to altair? I'd argue it's not a bad option to play with mpld3 in the short-term.

**Comment by rgieseke** [comment]
Did have a brief look at the mpld3d demos, which look quite nice -- we could give it a try for embedding, but it seems mpld3 is in low-maintainance mode atm.

> Note: mpld3 is in the process of switching maintainers: feature requests & bug reports are likely to be delayed. If you are interested in contributing to this project, please contact one of the repository owners.

**Comment by perrette** [comment]
I now have ranking maps functionality:

```
- 2 degrees warming, land:

{{rankingmap('land_abs_temp', 2)}}
{{rankingmap('land_abs_temp', 2, method='value')}}

- 2 degrees warming, population:

{{rankingmap('pop_abs_temp', 2)}}
{{rankingmap('pop_abs_temp', 2, method='value')}}

- End of century in RCP 6.0, land:

{{rankingmap('land_abs_time', '2081-2100', scenario='rcp60')}}
{{rankingmap('land_abs_time', '2081-2100', scenario='rcp60', method='value')}}

- End of century in RCP 6.0, population:

{{rankingmap('pop_abs_time', '2081-2100', scenario='rcp60')}}
{{rankingmap('pop_abs_time', '2081-2100', scenario='rcp60', method='value')}}
```

Note the '...' text quotes for the variable name, when `lineplot` syntax is:

```
{{lineplot(land_abs_time)}}
{{lineplot(land_abs_temp)}}
```
since in the latter case `land_abs_time` matches the corresponding json file for one area, while `rankingmap` applies to all `land_abs_time` variables across all areas.

**Comment by perrette** [comment]
An example is here: https://gitlab.pik-potsdam.de/isipedia/extremes/blob/master/cube/drought/future-projections/world/drought-world.md

**Comment by perrette** [comment]
I now have the `countrymaps` included (matplotlib).
e.g.
`{{countrymap(pop_abs_time, '2081-2100', scenario='rcp60')}}`

same path for the examples:
https://gitlab.pik-potsdam.de/isipedia/extremes/blob/master/cube/drought/future-projections/AFG/drought-AFG.md

**Comment by perrette** [comment]
Hi Robert, 

To have the result  that you requested:
> `![The figure description](mychart.vl.png){#fig:the-figref}`

I'd probably go for:
- `{{lineplot('land_abs_time', id='the-figref', caption='The figure description')}}`

I'd further suggest that `id` determine the figure ID that enters in the file name. I.e. the actual result would be:

`![The figure description](the-figref.vl.png){#fig:the-figref}`

OK?

**Comment by perrette** [comment]
@rgieseke , what about some more specifc information in a separate file `figures/html.json`.For instance:
```
{
    'figures' : [
    {
        "id":  #figid,
        "backend": "vega-lite",
        "static" : "figures/#figid.png",
        "json" : "figures/#figid.json",
    },
   ... 
   ]
}
```
or  the like?

**Comment by perrette** [comment]
Or better:

```
{
    #figid : [
    {
        "backend": "vega-lite",
        "json" : "figures/#figid.json",
    },
    {   
       "backend" : "static",
        "static" : "figures/#figid.png",
    }
   ... 
   ]
}
```

**Comment by rgieseke** [comment]
In principle i like the separate JSON idea, i had also thought about reading metadata like size or Vega-Spec version number from the JSON we already have ... but i struggled with the path in the Pandoc filters and it felt not worth the trouble

> ![The figure description](the-figref.vl.png){#fig:the-figref}

This looks quite good to me!

That would mean we only need
```
{{lineplot('land_abs_time', caption='The figure description')}}
```

**Comment by perrette** [comment]
I see, no worry.  
Yes exactly. And optionally the `id=` to specify a more meaninful one.

**Comment by rgieseke** [comment]
The caption could also come from the JSON metadata, just using the `title` field or something.

**Comment by perrette** [comment]
Good, yes, for the default value.

**Comment by rgieseke** [comment]
This has worked great so far! I think we'll need `vl.json` along with a `.png` and `.pdf`version.

- png for the md-preview on Gitlab/GitHub *and* for showing a static image in IE11 (Edge seems to work well the Vega figures)
- pdf for the LaTeX PDFs because they scale nicely

**Comment by perrette** [comment]
I suppose that is something that I should produce in the templating system, right? 
altair is pretty slow !

**Comment by rgieseke** [comment]
Yes, that could be slow, because for the PNG and PDF altair-save is shelling out to `node`/`vega-cli` tools i guess ...

**Comment by perrette** [comment]
I also needed to download some chromedriver (10 Mb) to be able to do this.

**Comment by rgieseke** [comment]
I'm not sure how this works, there are two ways to generate the PNG/PDFs, one is with Selenium and a headless browser (Firefox/Chrome i guess) or with `node`, which i enforced with `method='node'`, though this might require chromedriver as well.

**Comment by perrette** [comment]
Good to know, will try this out.

**Comment by rgieseke** [comment]
This should be the relevant doc:

https://github.com/altair-viz/altair_saver/#nodejs

**Comment by rgieseke** [comment]
I think we could also shift the PDF creation to the PDF creation step in the website repo - this would avoid having to store it once more.

PNG would be in the report repo along with the original vl.json.
- PNG for preview in repo and as fallback for IE11

**Comment by perrette** [comment]
Agreed. But what about the PDF figure? I could also save it as svg, but thinking about it, I reckon we are more interested in having a convenient format than high-resolution figures. The figures are intended mostly to be visualized online, anyway. I would not worry about high-resolution or fully scalable figures. So interactive html + static png is a good compromise I think.

**Comment by rgieseke** [comment]
The PNGs in the report PDF looked crap, one could probably find a compromise by producing high-resolution PNGs but PDF plots in the LaTeX look great and are scaleable ...

**Comment by perrette** [comment]
That's for sure !
Matplotlib pngs (saved at 100 dpi) look good in the PDFs. 
I did not specify anything for altair. I'm sure it's possible.
By the way I have still trying to read geojson data in altair, but that wont take much longer hopefully (I'm also learning about topojson and geopandas... since they all seem to work together).

**Comment by perrette** [comment]
Seems that `scale_factor= X` fixes it (https://github.com/altair-viz/altair/issues/909)

**Comment by rgieseke** [comment]
Good point with `scale_factor`, if we have one format less to deal with the better!

**Comment by perrette** [comment]
Hmm. scale_factor=2 is better, probably.

- Unscaled:
https://gitlab.pik-potsdam.de/isipedia/extremes/blob/5298c57a31f6476fb46e9cb101cc0a8ef93f1410/cube/drought/future-projections/AFG/figures/831111-vl.png

- Scaled (x2):
https://gitlab.pik-potsdam.de/isipedia/extremes/blob/d5a69014c5c8fb7557b1ffcb6e2b8d9f98ab4b2d/cube/drought/future-projections/AFG/figures/831111-vl.png

- SVG:
https://gitlab.pik-potsdam.de/isipedia/extremes/blob/d5a69014c5c8fb7557b1ffcb6e2b8d9f98ab4b2d/cube/drought/future-projections/AFG/figures/831111-vl.svg

**Comment by perrette** [comment]
(AFG is as scaled png on the master)
Let me see if node does something better.

**Comment by perrette** [comment]
I added a svg fig in the markdown next to the first line plot fig in AFG, for comparison.
It does not display on gitlab and is larger overall.

204K	cube/drought/future-projections/AFG/figures/831111-vl.json
292K	cube/drought/future-projections/AFG/figures/831111-vl.png
500K	cube/drought/future-projections/AFG/figures/831111-vl.svg

If better, that could possibly be produced from vega-json along with the PDF by the server.

**Comment by perrette** [comment]
Having trouble to install vega via node...
Hanging at:
```
npm install vega-lite vega-cli canvas

> canvas@2.6.1 install ...
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
```
Is it worthwhile installing the latest nodejs (v10) instead of the ubuntu apt latest (v8) ?

**Comment by rgieseke** [comment]
Could be, I think I have node installed via snap 

Jochen recommended nvm as well

**Comment by perrette** [comment]
I did, and things went better. Well, I'll play with node later. Focusing on the map now.

**Comment by perrette** [comment]
That was as simple as:

`source = alt.Data(values=js['features'])`

![image](https://user-images.githubusercontent.com/1402264/75987791-cfd18c00-5ef0-11ea-97e0-844ddb7065f7.png)

Need 1h break, will come back to it then.

**Comment by perrette** [comment]
![image](https://user-images.githubusercontent.com/1402264/75993748-40c97180-5efa-11ea-9d26-5a0fc690e576.png)

Alright, I get how the encode/transform works (nice). Let me include that into isispedia.

**Comment by rgieseke** [comment]
Beauty!

**Comment by perrette** [comment]
Very strange, I get that fig when saving to PNG:

![image](https://user-images.githubusercontent.com/1402264/76000162-98b8a600-5f03-11ea-9cf0-1ceb64c459df.png)

(e.g. zoom on Madagascar)

**Comment by perrette** [comment]
These sort of spikes also occur when I save as svg from the jupyter notebook. Weird.

**Comment by rgieseke** [comment]
Maybe too many elements in the border which overlap?

**Comment by rgieseke** [comment]
https://github.com/mapbox/geojson-tidy

**Comment by perrette** [comment]
In fact the interactive figure looks good. The problem comes from saving.
I have the issue even if I simplify quite a bit.
It is solved if I remove the stroke.

![image](https://user-images.githubusercontent.com/1402264/76003052-d3bcd880-5f07-11ea-9c55-66f982ab5725.png)

**Comment by rgieseke** [comment]
Looks nice as well :-)

**Comment by perrette** [comment]
I now added ascending/descending prop.
I'd like to try various color maps, too.
In any case, I have now updated the world report with these figures for testing online, if you wish.

**Comment by perrette** [comment]
Ow. The json files for the global maps make ~10M each !
Can you try and see if that works? Otherwise I'll need to simplify (that is fine as well).

**Comment by perrette** [comment]
The nice thing now is that both rank and value can be accessed from one map !
We could also use such as map as selector... with various stats shown for each country.
Note sure if we can tweak pan/zoom somehow, worse case on mouse event...
Let's make a separate issue for that.

**Comment by rgieseke** [comment]
Great, by default zooming wasn't available in Vega-Lite (but there was an example for vanilla Vega).

10M sounds too big (users might be on a mobile connection ... but there are many digits so maybe truncating those might be a first step? Otherwise i think the natural earth files weren't so big, were they?

**Comment by perrette** [comment]
I solved that issue with shapely simplify + truncating indeed ! (as we discussed yesterday), to 0.5K size. The issue now arise with the heatmap (raster).
Any way I close that issue that got too large and unspecific
