### ISSUE TITLE
user extensions

### ISSUE THREAD

**Issue by perrette** [ISI-MIP/isipedia-library#2]
Every study is different, and not everything shall be contained in the library.
Think how to interface study-specific code and isipedia library for template generation.
That should permit study-specific figures, aliases, data files.

See e.g. [runner](https://github.com/perrette/runner) for inspiration.

**Comment by rgieseke** [comment]
Good point ...! For simple studies figure generation code could be just along the figure.

**Comment by perrette** [comment]
I am not sure what you mean. 

The simplest method I can think of is to have a `custom.py` module in the same directory from which `python -m isipedia.textgenerator` is called, which would be made accessible within jinja2 as `{{custom.whateverfunction()}}`.

A difficulty here is that the context changes as the function is executed from within a country folder. 
The first think I could think of for `custom.py` was something like:

```python
from isipedia.figures import CustomFig

ISIPEDIA_FIGURE_CLASSES = ['MyFig']  # communication with textgenerator

class MyFig(CustomFig):
    def __init__(self, folder):
        self.folder = folder   # country folder
         .... # load files and prepare data accordingly

    def __call__(self, a, b, c...):
        ' to be called within the jinja2 template '
        ...  # create the figure(s), save them, 
        return  '![...](...)'  appropriate figure insert
```

where `CustomFig` is a subclass of `SuperFig`. In SuperFig, the various things done in __call__ are broken down between figure generation+ saving the figure, and making the appropriate insert in the markdown. That can be done as well.

Alternatively, one could define a function whose first argument is the folder context (gives access to the folder as `context.folder`, and possibly other things), and use a decorator-like syntax.

```python
from isipedia.figures import isipediafigure

@isipediafigure(method='altair')
def myfig(context, a, b, c...):
        ''' to be called within the jinja2 template 
        '''
        ...  # load data from folder (`context.folder`), create the figure(s)
        return altair, figureID # return figure and figureID, the decorator will do the rest of the job depending on method
```
Here the isipediafigure decorator 1) tells textgenerator that this figure should be provided as `custom.myfig` and 2) modifies the output for appropriate insert, and the input so that the function is called in the template as `myfig(a, b, c)`.

Context could be user-provided as well, with say a `context_class` argument to `isipediafigure`, where context_class is a subclass of.
```
class Context:
   def __init__(self, folder):
      self.folder = folder
      ... # subclasses may make more things available here
```

Now this formulaiton of `context` could be exactly the kind of problem to be solved elegantly with [contextlib](https://docs.python.org/3/library/contextlib.html), just as `flask` uses. `context` would then not be provided as argument, but as top-level import"
```
from isipedia.custom import context, isipediafigure

@isipediafigure(method='altair')
def myfig(a, b, c):
    ...  # get data from `context`
    ... create the figures
    return altair_figure, figure_id
```
though I am not sure if it offers a clear advantage, and it leaves me wonder how to modify context so that it works with parallel processing (it flasks uses it, I guess that works).

**Comment by perrette** [comment]
@jochenklar are you familiar with that discussion?

**Comment by rgieseke** [comment]
I was just noting that i hadn't thought about this problem of coupling plotting code with articles before - you obviously have!
Was just thinking of the simple case without any dependency on isipedia-library.

In general, i've been thinking the "rendering" engines could also be activated with metadata frontmatter flags, e.g.

```
vega-lite: true
d3: true
```

**Comment by perrette** [comment]
What I propose is in line with what is already implemented, that's why I thought of that, but there are many alternatives. Of course, it is always possible to create the figures before hand in the cube repos, and just have an insert command compatible with what we otherwise use. But since I will probably be the one implementing it, I'd rather re-use what already exists inside the isipedia library. That can be made clean and at least as flexible with the `@isipediafigure` decorator and possibly a context manager.

As far as coupling is concerned, things can also be taken at a higher level with a ISIpediaTemplate class with appropriate subclassable methods, that can be used to create a study-specific executable. That is more flexible that having to fit into the `isipedia.textgenerator` script.

For the next step I think a custom.py file for figures is the most straightforward approach for me, but I'd like to formalize a sub-classable `ISIpediaTemplate` class in the future.

As far as the parameter are concerned, I tend to favour running a script with explicit arguments that can be changed on the fly.

**Comment by perrette** [comment]
> I was just noting that i hadn't thought about this problem of coupling plotting code with articles before - you obviously have!

I had to for this [runner](https://github.com/perrette/runner) project of mine...

**Comment by perrette** [comment]
The reason why I propose this tighter coupling is also to allow experimentation in individual studies, while keeping things in a form that can be integrated into the main library later, just copy pasting the few lines of code. I.e. I'd use the same syntax in the main isipedia code.
